### ISSUE TITLE
Allow Scienists on EVA to reset samples

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#10]
A scientist should be able to carry a limited amount of the "Sample Material" resource. If he has enough of the stuff, he should be able to "refill" a sampling experiment.

Once the stuff is in the experiment, it cannot be extracted any more, it has to be used up.

**Comment by UsernamesAreAlwaysTaken** [comment]
See comment on Issue #9. This may be unnecessary if implemented as described there

**Comment by SirMortimer** [comment]
yup.
