### ISSUE TITLE
KAC support?

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#16]
Add KAC alarms for long-running experiments?

Sample code:
https://github.com/mwerle/OrbitalMaterialScience/commit/3cfcbfca7ba125a64f1e061a925bdec9952c692f

**Comment by UsernamesAreAlwaysTaken** [comment]
please make it optional, don't forcefully add KAC alarms by default. stuff will get spammed.

**Comment by SirMortimer** [comment]
not doing it.
