### ISSUE TITLE
secondary animation slot (deploy_anim and running_anim; stock doesn;t need 2 slots, plenty of mods do)

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#21]

**Comment by UsernamesAreAlwaysTaken** [comment]
The secondary animation is probably a transform, and also needs pivots defined i believe, the same way solar panels work. I'm not sure how animations are handled by the game, but i assume it's similar.

**Comment by UsernamesAreAlwaysTaken** [comment]
want to have some fun?

`    animationName = Deploy
    useSampleTransforms = true
    sampleTransformName = Canister
    dataRemovalAnimation = true
    dataRemovalAnimationReverse = true
    dataRemovalAnimationName = Extract`

this is RestockPlus. 2 animations +1 transform.

**Comment by UsernamesAreAlwaysTaken** [comment]
even more fun:

    animationName = Deploy
    useSampleTransforms = true
    sampleTransformName = Experiments_Disappearing
    useReplacementTransforms = true
    replacementTransformName = Experiments_Used
    replacementTransformScale = 1.0
    dataRemovalAnimation = true
    dataRemovalAnimationReverse = true
    dataRemovalAnimationName = Extract

**Comment by UsernamesAreAlwaysTaken** [comment]
the other 2 restock parts also have 2 animations and 2 transforms. I have no idea where to even begin.

(restock-materialbay-radial-1, restock-goocanister-625-1)

**Comment by UsernamesAreAlwaysTaken** [comment]
At this point, judging by how complex DM's mods are, i suggest leaving Experiment as is, without the multiple animations, and introducing a second custom module that takes care of all this stuff, otherwise it'll get very bloated very quick.

The deployment works as is, but that's just about it.

**Comment by SirMortimer** [comment]
There now is a `anim_loop`
Not exactly satisfied with the result yet, but it will be that

**Comment by SirMortimer** [comment]
maximum effort.
