### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#23]
IF you're willing to touch configure:
-default Setup for all slots , such as default=SETUP[name]

-disabling subdependencies once a setup is removed. 
	to explain: nesting configures works, with a major bug: CONFIGURE - select from available setups, these setups then provide a range of experiments. Once the setup in the main configure is changed, the previously selected 
	experiments don't get removed.
		EXAMPLE: Configure Science Instrument Unit - Atmospheric Package selected
						Configure Atmospheric Package - Presmat Barometer Selected
				Change Science Instrument Unit SETUP to - Sensors
						Configure Sensors - Geiger Counter
						
			RESULT: both Presmat Barometer AND the Geiger counter are present on the part.

**Comment by SirMortimer** [comment]
might be fixed, but didn't really test it.

**Comment by UsernamesAreAlwaysTaken** [comment]
fixed.
