### ISSUE TITLE
Infinite storage option for HDD's

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#24]
Be able to set infinite storage for hard drives/sample containers.
Suggested: allow for dataCapacity and sampleCapacity = -1 for example, which should signify infinite storage.

This is done in order to revert the HDD nerf if people would like to keep the old science mechanic that was shipped with kerbalism prior to this rework.

**Comment by SirMortimer** [comment]
done.
