### ISSUE TITLE
Sum up the storage capacities of all hard drives on a vessel

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#25]
Currently, samples/data go into the biggest or selected HDD/Sample Container. If vessel has multiple parts with HDDs, the storage capacity is still limited to the selected drive's capacity. Others are not factored in.

Suggestion is, as long as there are multiple drives on the ship, allow their storage to be summed up. (I have no clue how to deal with separation/undocking, you'd have to keep track of what was stored where somehow)

**Comment by SirMortimer** [comment]
should work now.
