### ISSUE TITLE
Storing samples and data separately in different containers.

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#26]
Currently, probe cores cannot store samples, and the science box cannot store data.

Depending on which is the current active drive, the vessel can either store data only, or samples only, but not both, as they're in separate parts, thus separate drives.

See the #25  this could be a possible sollution. 2 birds with 1 stone.

https://cdn.discordapp.com/attachments/561476570129235983/563353410993127425/unknown.png

**Comment by SirMortimer** [comment]
there's no such thing as a "currently active drive". Samples should store the data in whichever drive is available, starting from the one with the largest capacity. If that doesn't work, it needs to be fixed right away

**Comment by UsernamesAreAlwaysTaken** [comment]
eg. Stayputnik+ Science box+ a bunch of mystery goo, Cannot run goo because not enough storage, while it clearly does have the science box.

Something broken for sure.

**Comment by UsernamesAreAlwaysTaken** [comment]
Fixed.
