### ISSUE TITLE
Transfer Data Here is funky

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#27]
Transfer Data Here - well, it does what it says, it transfers the data there. but stuff still writess data on the root part i believe.

check the gif :
![Test 6](https://user-images.githubusercontent.com/48958828/55582093-81cb6b80-5716-11e9-9b9a-0a8e2b694f0a.gif)

**Comment by SirMortimer** [comment]
data is always written to a suitable drive, there is no way to control that. it just fills up whatever is available.
