### ISSUE TITLE
BAGS

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#28]
big bug. pls fix.
![Untitled](https://user-images.githubusercontent.com/48958828/55583851-c9ec8d00-571a-11e9-8c26-f735f99e185a.png)

**Comment by UsernamesAreAlwaysTaken** [comment]
it's a bug because my brain is throwing nullrefs. game itself is fine.

**Comment by SirMortimer** [comment]
<img width="204" alt="Bildschirmfoto_2019-04-04_um_22 52 23" src="https://user-images.githubusercontent.com/43166475/55587877-ad595080-572c-11e9-9b32-18158f53df0b.png">
