### ISSUE TITLE
Keeping mass in check with sampling experiments. 

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#29]
Mass movement should be as follows:
For the ones that implement sample_collecting = True
Instrument private drive->lab->airlock

for the ones that implement sample_collecting = False
sample_reservoir->lab->sample_reservoir

**Comment by SirMortimer** [comment]
I think it's fixed, but can't test bc my lab is bonkers. probably the config is haywire
