### ISSUE TITLE
SCANSAT

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#3]
With scansat, you scan a planet to generate a map. When finished, or whenever you feel like it, you click the "Analyze Data" button on the scansat scanner. That button essentially is a "run experiment" button that generates science value from the scanned map.

Ideally, the scanner would continuously sample data while it runs, and stop scanning when the data cannot be stored. The "Analyze data" button should disappear.

**Comment by UsernamesAreAlwaysTaken** [comment]
if you manage to somehow make this work, via a custom module, I could probably patch the M700 Orbital Survey Scanner to work in a similar fashion as scansat scanners. Need to check how the overlays are generated, and if Scansat can keep track of it partially.

Needs work, but probably could be done.

**Comment by SirMortimer** [comment]
it is a custom part module, but it directly interacts with scansat and only works with that mod. supporting other stuff will require something else.
