### ISSUE TITLE
WTB Body:x changes

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#33]
Could use a way to remove a body from the possible situations.

E.G, ground base science, it makes little to no sense to be able to do that on kerbin.

Something in the format 
requires = Body:!Kerbin or NotKerbin.

Another request would be being able to specify multiple bodies at the same time (you mentioned in commens in your code that only one body can be specified per experiment). orbital habitation around kerbin, mun and minums only, pointless to have it available for other planets as you'd be spending more time getting there than the duration of the experiment itself.

**Comment by SirMortimer** [comment]
These are now supposed work:
`Body:Duna;Eve;Gilly` (note: separate with semicolon ; )
`Body:!Kerbin`
