### ISSUE TITLE
ArgumentOutOfRangeException when placing parts with Configure in symmetry mode.

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#35]
![NRE](https://user-images.githubusercontent.com/48958828/55687367-25f62200-5964-11e9-8607-09a791b7dc74.gif)

[EXC 18:34:28.531] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[PartResource].get_Item (Int32 index)
	DictionaryValueList`2[System.Int32,PartResource].At (Int32 index)
	PartResourceList.get_Item (Int32 index)
	Part.OnCopy (.Part original, Boolean asSymCounterpart)
	EditorLogic.createSymmetry (Int32 mode, .Attachment attach)
	EditorLogic.<SetupFSM>m__D ()
	KerbalFSM.UpdateFSM ()
	EditorLogic.Update ()

**Comment by UsernamesAreAlwaysTaken** [comment]
Part.OnCopy (.Part original, Boolean asSymCounterpart)

is it because none of the parts have the symmetry thingy specified? (you mentioned something about changing how symmetry works with configure), possibly add a default to avoid log spam, which can be then changed through MM patches

**Comment by SirMortimer** [comment]
nah, that's in Kerbalism 2.1 as well. I always took that for a new feature of KSP...

**Comment by SirMortimer** [comment]
but I can confirm. the bug is in the configure module. who would have thought

**Comment by SirMortimer** [comment]
it's not configure, it was the way we added resources dynamically.

found a fix.
