### ISSUE TITLE
Planner Display Error

### ISSUE THREAD

**Issue by Cruesoe** [SirMortimer/Kerbalism#39]
On Biome change experiments marked as waiting change to, and remain on, 0%.
For example on launch, goo set to waiting.  Flying low goo already collected in a previous mission.  As soon as I launch goo changes to 0% and remains there.  No data being collected as expected.  Only planner is reading 0% rather than 'waiting' still.

![beforelaunch](https://user-images.githubusercontent.com/49525542/55963444-beddb380-5c6a-11e9-9626-239bce208b54.png)
![afterlaunch](https://user-images.githubusercontent.com/49525542/55963468-cf8e2980-5c6a-11e9-835a-9524a7bca62d.png)
![afterlaunch2](https://user-images.githubusercontent.com/49525542/55963480-d4eb7400-5c6a-11e9-8753-efc057c95961.png)

**Comment by Cruesoe** [comment]
See further, planner does not match what experiments are doing.
Here the temperature is gathering data from the grassland and planner says waiting.

![screenshot4](https://user-images.githubusercontent.com/49525542/55965063-be92e780-5c6d-11e9-93a8-2ada9c604be3.png)

**Comment by SirMortimer** [comment]
should be fixed
