### ISSUE TITLE
Moar situations

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#4]
Currently the science system is based on the stock KSP experiment. I'd keep it that way for this release, but after that we could replace stock experiment definitions with our own. Reason why I'm not feeling too good about doing it now is 3rd party mods that work with experiments. For exmple, I have no clue about how much DMOS relies on stock KSP Experiment Definitions, if it does at all.

What we could do:

1. Separate the Kerbalism Experiment definition from the Kerbalism Experiment Part Module. A rename might be in order, too (Experiment might be too generic and conflict with other mods).
2. Pimp the Kerbalism experiment definition with new Situations. Like "In Polar Orbit", "In Stationary Orbit", "During reentry" + all/revamped situations from stock. The list should be of arbitrary lenght (no hard coded situation count limit, this pretty much rules out "situationMask" and other bullshittery).
3. Delegate the definition and implementation of situations to a static class that could be replaced by other mods (looking at you, RO).

**Comment by UsernamesAreAlwaysTaken** [comment]
In general, Experiment should be pimped a bit to be able to support most major functions of other mods. This would make it a go-to module for defining complex experiments, even by other modders.
This would require a separation of experiment from kerbalism though.
