### ISSUE TITLE
WTB the same treatment for samples

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#43]
long term sample analyzing while collecting is iffy.
If you analyze the samples faster than they get collected, analysis just stops, and has to be restarted manually.

Can the samples get the same treatment as the data transmission? keep them flagged for analysis if the experiment has sample_collecting = True
the values in this example are way off, but the point stands.
![grrrrr](https://user-images.githubusercontent.com/48958828/56106578-ce465080-5f39-11e9-8151-62d0d61dacf1.gif)

**Comment by SirMortimer** [comment]
mh. i added a preference setting that does the same as the auto-transmit-science option. it will be auto-analyze-samples (default is on). so whenever a new file is created, that flag is set to whatever is defined in the preferences.
