### ISSUE TITLE
Hide Operation if the field is empty

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#47]
![image](https://user-images.githubusercontent.com/48958828/56251490-b989ca00-60ab-11e9-9f48-074f6ee842f7.png)

that should probably apply to all experiment fields in the configure UI. if the field is empty , hide it.

**Comment by UsernamesAreAlwaysTaken** [comment]
actually that's wrong. I have it set to false (forcing unmanned experiments to be unmanned, therefore it's displaying it. No may be a bit confusing though. halp?)

**Comment by SirMortimer** [comment]
you can't force an unmanned experiment that way. false is the same as leaving it empty.

**Comment by SirMortimer** [comment]
should work now. pls test
