### ISSUE TITLE
Labs are broken

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#48]
![asdasdasd](https://user-images.githubusercontent.com/48958828/56330484-135bc400-6180-11e9-9ce6-27b7e05f0042.gif)
^ labs don't process samples. like at all.

**Comment by UsernamesAreAlwaysTaken** [comment]
Note: latest version as of 02:18 GMT

**Comment by SirMortimer** [comment]
bob got lazy

**Comment by SirMortimer** [comment]
fixed.
