### ISSUE TITLE
KAS changes to a craft deletes all samples

### ISSUE THREAD

**Issue by hermanolhc** [SirMortimer/Kerbalism#49]
Kerbalism 3.0 beta. Currently changing anything about a craft with KAS, e.g. adding a solar panel, will delete all sample data from the craft. All experiments will show insufficent hard drive space until the game is reloaded.

**Comment by SirMortimer** [comment]
that might be fixed with alpha.4 (just uploaded a minute ago), could you take another look with that version?

**Comment by hermanolhc** [comment]
The problem is fixed with the current download. Data samples in the test capsule stayed after changes to the craft. Data in removed and reattached parts was lost however. This seems fine to me, great job!
