### ISSUE TITLE
3.0 Upgraded antennae break CommNet

### ISSUE THREAD

**Issue by hermanolhc** [SirMortimer/Kerbalism#51]
With the current version of Kerbalism the CommNet breaks regularly. Only a full restart of the game will reactivate CommNet.

The issue seems to stem from
`UPGRADESAPPLIED{upgrade = Antenna-Upgrade1}` lines in the save-file. 
Removing the lines from the save and removing the Kerbalism antenna upgrades in AntennaConfigs.cfg solves the problem.
The same issue is described herefor another mod using antenna upgrades: [link](https://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-v0161-beta-6272018-144/&page=67)

**Comment by steamp0rt** [comment]
oh boy, ksp bug?

**Comment by SirMortimer** [comment]
i never had that, not once.

**Comment by SirMortimer** [comment]
@hermanolhc which KSP version did you use?

**Comment by hermanolhc** [comment]
@SirMortimer I use KSP 1.6.1

**Comment by SirMortimer** [comment]
Ah damnit. If you had used a fossilized verison of KSP I might have blamed it on that, but to me this looks like a bug in stock KSP. It means we'll have to drop antenna upgrades, which is a bit of a bummer.

**Comment by hermanolhc** [comment]
With the newest update 4 errors are thrown:


`[LOG 2019-04-23 15:47:45.803] Applying update Kerbalism/System/ScienceRework/Groups/Upgrades/@PARTUPGRADE[Antenna-Upgrade1]:NEEDS[FeatureScience] to Kerbalism/System/ScienceRework/Groups/Upgrades.cfg/PARTUPGRADE

[ERR 2019-04-23 15:47:45.803] Error - Cannot parse variable search when replacing (%) key techRequired = #$@KERBALISM_ANTENNA_RATES/Upgrades/FirstUpgradeTech$

[ERR 2019-04-23 15:47:45.803] Error - Cannot parse variable search when replacing (%) key entryCost = #$@KERBALISM_ANTENNA_RATES/Upgrades/FirstUpgradeEntryCost$

[LOG 2019-04-23 15:47:45.803] Applying update Kerbalism/System/ScienceRework/Groups/Upgrades/@PARTUPGRADE[Antenna-Upgrade2]:NEEDS[FeatureScience] to Kerbalism/System/ScienceRework/Groups/Upgrades.cfg/PARTUPGRADE

[ERR 2019-04-23 15:47:45.803] Error - Cannot parse variable search when replacing (%) key techRequired = #$@KERBALISM_ANTENNA_RATES/Upgrades/SecondUpgradeTech$

[ERR 2019-04-23 15:47:45.803] Error - Cannot parse variable search when replacing (%) key entryCost = #$@KERBALISM_ANTENNA_RATES/Upgrades/SecondUpgradeEntryCost$`

**Comment by hermanolhc** [comment]
Problems don't occur with latest alpha.
