### ISSUE TITLE
In Mother RUSSIA, Data Capacity increases instead of decreases.

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#53]
![20190422_204426](https://user-images.githubusercontent.com/48958828/56543822-81cac880-656a-11e9-80c2-529de5afb83f.jpg)

117%. (top of the data window).

P.S: Let me guess. Infinite drives don't play well, do they?

P.P.S: Not my picture. I know how to take a screenshot.

**Comment by SirMortimer** [comment]
yup. removed the percentage for unlimited drives.
