### ISSUE TITLE
Editor: it is possible to start the same experiments many times

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#6]
Currently, you can cheat the system by running an experiment 3 times at the same time. While this will not yield additional science value, it will reduce the experiment duration by a factor of 3.

Experiments should have a limit that defines how often they can be run in parallel on a vessel. Default value for that limit should be 1.

**Comment by UsernamesAreAlwaysTaken** [comment]
The fix only works if experiments are started in flight. 
If they're already started in editor, before launch, they will run simultaneously.

**Comment by SirMortimer** [comment]
Tricky to fix (or I don't know how), postponing.

**Comment by SirMortimer** [comment]
Found a solution :)
