### ISSUE TITLE
Sell surface samples for money

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#8]
If a surface sample is returned to KSC and there is no scientific value in analyzing them, they should yield credits. Credit value dependant on the science multiplicator of the body they came from.

**Comment by UsernamesAreAlwaysTaken** [comment]
Suggestion: exponential decaying values for subsequent sample returns, even if they have no more scientific value.

e.g. 100% for the first sample, 50% for the 2nd, 25% for the 3rd and so on.
